name: Tag Version from pyproject.toml

on:
  workflow_dispatch:  # Manually trigger this action
  push:
    branches:
      - main  # Trigger automatically when pushing to main

jobs:
  tag-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Needed to create tags properly

      - name: Extract version from pyproject.toml
        id: get_version
        run: |
          VERSION=$(grep 'version =' pyproject.toml | head -1 | cut -d '"' -f2)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Detected version: $VERSION"

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create and push tag
        run: |
          if git rev-parse "v$VERSION" >/dev/null 2>&1; then
            echo "Tag v$VERSION already exists. Skipping."
          else
            git tag v$VERSION -a -m "Release version $VERSION"
            git push origin v$VERSION
          fi
